eureka:
  instance:
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8090

spring:
  cloud:
    discovery:
      enabled: true
  application:
    name: notification-service
  