eureka:
  instance:
    preferIpAddress: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8060

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          spring:
            provider: spring
            client-id: oidc-client
            client-secret: secret
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "http://127.0.0.1:8060/login/oauth2/code/spring"
            scope: openid, profile
        provider:
          spring:
            authorization-uri: http://localhost:9000/oauth2/authorize
            issuer-uri: http://localhost:9000
            token-uri: http://localhost:9000/oauth2/token
