eureka:
  instance:
    preferIpAddress: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 9000

spring:
  cloud:
    discovery:
      enabled: true
  application:
    name: authorization-server
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.security: DEBUG